In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Cleaned-Data.csv")
df.head(10)

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   
5      1          1          1                        1            1   
6      1          1          1                        1            1   
7      1          1          1                        1            1   
8      1          1          1                        1            1   
9      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   
5             0      1                 1           1         1  ...   
6             0      1                 1           1         1  ...   
7             0      1                 1           1         1  ...   
8             0      1                 1           1         1  ...   
9             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0   
1            1                   0              1                  0   
2            1                   0              1                  0   
3            1                   0              0                  1   
4            1                   0              0                  1   
5            1                   0              0                  1   
6            1                   0              0                  0   
7            1                   0              0                  0   
8            1                   0              0                  0   
9            1                   0              0                  0   

   Severity_None  Severity_Severe  Contact_Dont-Know  Contact_No  Contact_Yes  \
0              0                0                  0           0            1   
1              0                0                  0           1            0   
2              0                0                  1           0            0   
3              0                0                  0           0            1   
4              0                0                  0           1            0   
5              0                0                  1           0            0   
6              0                1                  0           0            1   
7              0                1                  0           1            0   
8              0                1                  1           0            0   
9              1                0                  0           0            1   

   Country  
0    China  
1    China  
2    China  
3    China  
4    China  
5    China  
6    China  
7    China  
8    China  
9    China  

[10 rows x 27 columns]

In [3]:
x=df.iloc[:,0:13].values
y=df.iloc[:,13].values

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.25,random_state=0)


In [5]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)



In [6]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
y_pred


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [7]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[63331,     0],
       [15869,     0]], dtype=int64)

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7996338383838384

In [9]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89     63331
           1       0.00      0.00      0.00     15869

    accuracy                           0.80     79200
   macro avg       0.40      0.50      0.44     79200
weighted avg       0.64      0.80      0.71     79200



C:\Users\mylie\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylie\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mylie\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
print('Confusion matrix :','\n',cm)

print('\nAccuracy :',accuracy_score(y_test,y_pred))

print('\nSensitivity : ', cm[0,0]/(cm[0,0]+cm[0,1]) )
 
print('\nSpecificity : ', cm[1,1]/(cm[1,0]+cm[1,1]))

Confusion matrix : 
 [[63331     0]
 [15869     0]]

Accuracy : 0.7996338383838384

Sensitivity :  1.0

Specificity :  0.0


In [11]:
# import sklearn.metrics as metrics

# # TP = confusion[1,1] # true positive 
# # TN = confusion[0,0] # true negatives
# # FP = confusion[0,1] # false positives
# # FN = confusion[1,0] # false negatives


#     cm1 = metrics.confusion_matrix(y_test,y_pred)
#     total1=sum(sum(cm1))
#     Accuracy = (cm1[0,0]+cm1[1,1])/total1
#     Specificity = cm1[0,0]/(cm1[0,0]+cm1[0,1])
#     Sensitivity = cm1[1,1]/(cm1[1,0]+cm1[1,1])
#     cutoff_df.loc[i] =[ i ,Accuracy,Sensitivity,Specificity]
#     cutoff_df.loc[i]